management:
     endpoints:
          web:
            exposure:
               include: "*"

spring:
     config:
         import: "optional:configserver:http://localhost:8091"
application:
         name: spring-cloud-config-client-db

server:
  port: 8585